### ISSUE TITLE
 RecordsService.addDatastream is not a function

### ISSUE THREAD

**Issue by moisbo** [redbox-mint/sails-hook-redbox-pdfgen#8]
Hi!

I wonder if we can have a version that supports latest redbox development. After installing latest redbox-portal, creating a pdf fails because it cannot find **RecordsService.addDatastream**

Thanks,
Moises

**Comment by shilob** [comment]
Hi Moises,

The plugin doesn't support the backend-refactor branch yet.  I'll throw in a version to support this, while also providing backward compatibility. 

Shall keep you posted.

Regards,
Shilo

**Comment by shilob** [comment]
Hi Moises,

Version 1.2.3 for this plugin is now available, I've tested this with the 'backend-refactor' branch. 

Let me know how this goes.

Thanks!

**Comment by moisbo** [comment]
Thanks Shilo, plugin working good. Closing.
